img.shields.io has ERR_CONNECTION_RESET
tlvince/make-coverage-badge pull request #6
Opened 2019-05-16 16:21 UTC by sakharovsergey

2019-05-16 16:24 UTC, tlvince commented
Seems fine here?

```
❯ curl -I https://img.shields.io/badge/build-passing-brightgreen.svg
HTTP/2 200
date: Thu, 16 May 2019 16:23:46 GMT
content-type: image/svg+xml;charset=utf-8
set-cookie: __cfduid=d2618b678bcc99ff86bb2e49443b6d0721558023826; expires=Fri, 15-May-20 16:23:46 GMT; path=/; domain=.shields.io; HttpOnly
cache-control: max-age=86400
last-modified: Mon, 13 May 2019 12:16:27 GMT
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4d7eb2b10eb83474-LHR
```

2019-05-16 16:29 UTC, sakharovsergey commented
```
> $ curl -vI https://img.shields.io/badge/build-passing-brightgreen.svg                                                                                                  [±master ●]
*   Trying 104.28.20.21...
* TCP_NODELAY set
* Connected to img.shields.io (104.28.20.21) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to img.shields.io:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to img.shields.io:443 
```

2019-05-16 16:34 UTC, sakharovsergey commented
![Снимок экрана 2019-05-16 в 21 32 04](https://user-images.githubusercontent.com/16402730/57871159-21a20c00-7822-11e9-9805-6e21d01fc707.png)
maybe only for Russia region 🤷🏼‍♂️

2019-05-20 10:05 UTC, tlvince requested changes
Some info on [Badgen vs shields.io](https://www.reddit.com/r/javascript/comments/91m0cn/badgen_fast_badge_generating_service_shieldsio/).

Am happy for this to go in, but could you fix the [lint warning](https://travis-ci.org/tlvince/make-coverage-badge/builds/533410793#L478) and reformat the commit message into [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) form? Thanks!

2019-05-20 10:05 UTC, tlvince commented on cli.js
> +  // return `https://img.shields.io/badge/Coverage-${coverage}${encodeURI('%')}-${colour}.svg`
Could you delete this line, please?

2019-05-20 10:07 UTC, tlvince commented
Could you also update the shields.io link and badges used in the readme?

2019-11-04 22:41 UTC, closed without merging